require("user.options")
require("user.vars")
require("user.keymaps")
require("user.split")
require("user.completion")
require("user.lsp")
require("user.telescopy")
require("user.treesitter")
-- require("user.clipboard")
require("user.comment")
require("user.nvimtree")
require("user.buffer")
require("user.lualine")
require("user.toggleterm")
