vim.loader.enable()
require'nvim-web-devicons'.setup()
require'user.options'
require'user.keymaps'
require'user.indent'
require'user.buffer'
require'user.project'
require'user.nvimtree'.setup()
require'user.treesitter'
require'user.telescope'
require'user.undotree'
require'user.lualine'
require'user.comment'
require'user.lsp'
require'user.gitsigns'
